### ISSUE TITLE
Let's add a contextual intro to all markdown pages in the planning folder.

### ISSUE THREAD

**Issue by howardroark** [openops/mom#1]
Let's ensure that if you look at a file in the planning folder that the first paragraph always gives you an intro as to why the topic is important to this project.

For example, the "push_notifications" file starts with an overview about push notifications  in terms of apple and google.  I think that would be better suited under a headline like "IOS vs Android".

The "Intro" should be more like.  "In practice MOM will need to be able to be able to check in with people even when they are not paying attention.  Push notifications will act as the best method to engage a smartphone user who may be preoccupied with something else.

**Comment by howardroark** [comment]
Any updates on this?

**Comment by Jordann** [comment]
The only markdown that doesn't have a contextual intro yet is NodeJS, since I haven't really researched into that yet.

**Comment by howardroark** [comment]
Cool! Go ahead and close any ticket that you are confident is mostly accounted for.  No need to keep things open just due to a few loose ends at this stage.
