### ISSUE TITLE
Defining the design that will make up activities and checkups.

### ISSUE THREAD

**Issue by howardroark** [openops/mom#13]
Since you are the compsci guy, I'd like you to spend some time thinking about the nature of how we could build the system for managing activities and checkups.

Perhaps it involves the creation of a message bus:  

http://oli.me.uk/2013/06/05/implementing-a-message-bus-in-javascript/

Maybe a dispatcher:

https://github.com/mrdoob/eventdispatcher.js/

Just want to make sure we explore all the design options before we go too far.

**Comment by Jordann** [comment]
sounds fun, ill document what i find

**Comment by howardroark** [comment]
Look into Events at the link below and start thinking about these could fit into our system.  Just looking for an option which produces result when changes in the data object occur. 

http://modeln.github.io/backbone.geppetto/#about/how-will-geppetto-help-my-project

Give the overview and the Events sections a read, let me know if you have thoughts.
