### ISSUE TITLE
Add links to components in main planning README

### ISSUE THREAD

**Issue by howardroark** [openops/mom#2]
Let's get these markdown files linking together a little better.

**Comment by Jordann** [comment]
should there be links back to the README from the other markdowns?

**Comment by howardroark** [comment]
That sounds good, maybe make "breadcrumbs" at the top.  Use relative links.

**Comment by Jordann** [comment]
github has its own breadcrumbs or would this be useful when on freesurface.org?

**Comment by howardroark** [comment]
Good point. Screw it, let's just have links on the main readme.  We can
link between files when the context is appropriate.
