### ISSUE TITLE
Ensure salt logic readies the web application to a useable state from initial provision.

### ISSUE THREAD

**Issue by howardroark** [openops/mom#21]
Make sure that when a new user clones the repo and runs `vagrant up` that they can begin development immediately.  All application packages and dependencies should be installed and running.

**Comment by Jordann** [comment]
Just cloned, the repo, ran `vagrant up`, then `vagrant ssh` and `fab dev`.

Everything seemed to work, although the address i used to connect was the local address http://192.168.1.132:8000/index.html

**Comment by howardroark** [comment]
What happens when you hit http://mom-Jord.local? No 8000.

**Comment by Jordann** [comment]
Still nothing, cant find the site

**Comment by howardroark** [comment]
Can you ping mom-Jord.local http://mom-jord.local:8000/ from the host
host system and the vm and post both results here?  Thanks!

**Comment by howardroark** [comment]
We are in a good place here.  Everything boots to a solid and useable state from clone through `vagrant up`.
