### ISSUE TITLE
Ensure that Virtual machine can run PhoneGap build process.

### ISSUE THREAD

**Issue by howardroark** [openops/mom#22]
After building a new virtual development environment ensure that a PhoneGap Android image can be built.  The image will later be sent to a device over http.

Record any missing steps in the Markdown documents.  Automation logic will be written based on these steps.

**Comment by Jordann** [comment]
https://source.android.com/source/initializing.html
http://roger.steneteg.org/294/android-development-without-eclipse/

Having troubles building for android. What i've done:

``` bash
sudo apt-get install git gnupg flex bison gperf build-essential \
     zip curl libc6-dev libncurses5-dev:i386 x11proto-core-dev \
     libx11-dev:i386 libreadline6-dev:i386 libgl1-mesa-glx:i386 \
     libgl1-mesa-dev g++-multilib mingw32 tofrodos \
     python-markdown libxml2-utils xsltproc zlib1g-dev:i386
sudo ln -s /usr/lib/i386-linux-gnu/mesa/libGL.so.1 /usr/lib/i386-linux-gnu/libGL.so
sudo apt-get update
sudo apt-get install openjdk-7-jre openjdk-7-jdk
sudo apt-get install ant
npm install phonegap -g
wget http://dl.google.com/android/android-sdk_r20-linux.tgz
tar -xvzf android-sdk_r20-linux.tgz
```

Then I updated my PATH for android tools, platform tools and java_home:

```
export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
export PATH="$PATH:/vagrant/salt/root/files/android-sdk-linux/platform-tools:/va
grant/salt/root/files/android-sdk-linux/tools"
```

now when i create a test project with `phonegap create testproject` and then try running it with `phonegap build android` I get an error with my android sdk.

I tried doing `android update sdk --no-ui` but the problem persists.

I think the problem resides in tools that are required but cannot be installed easily from the headless sdk manager.

If I go on to my laptop and run `android list sdk` I see:

``` bash
 1- Android SDK Tools, revision 23
   2- Android SDK Platform-tools, revision 20
   3- Documentation for Android SDK, API 19, revision 2
   4- SDK Platform Android 4.4.2, API 19, revision 3
   5- Samples for SDK API 19, revision 5
   6- Samples for SDK API 18, revision 1
   7- Samples for SDK API 17, revision 1
   8- Samples for SDK API 16, revision 1
   9- Samples for SDK API 15, revision 2
  10- Samples for SDK API 14, revision 2
  11- Samples for SDK API 13, revision 1
  12- Samples for SDK API 12, revision 1
  13- Samples for SDK API 11, revision 1
  14- Samples for SDK API 10, revision 1
  15- Samples for SDK API 8, revision 1
  16- Samples for SDK API 7, revision 1
  17- Glass Development Kit Preview, Android API 19, revision 8
  18- Android Support Library, revision 19.1
```

Although on the VM all i see when I use `android list sdk` is:

``` bash
   1- Android SDK Tools, revision 22.6.2
   2- Android SDK Platform-tools, revision 19.0.1
   3- Glass Development Kit Preview, Android API 19, revision 8
```

The one that stands out to me is:

```
4- SDK Platform Android 4.4.2, API 19, revision 3
```

**Comment by howardroark** [comment]
Are all of these steps available in the markdown document?  I'd like to cross compare and get a sense of the reason for each step.

**Comment by Jordann** [comment]
The only stuff not on the markdowns is the sdk stuff. I wanted to figure that part out before putting it into the markdown.

**Comment by howardroark** [comment]
Can you update the original comment with links to any resources that you used to produce the results?

**Comment by Jordann** [comment]
Alright I did, besides the 2 sources I listed I was usually just looking at stackoverflow on an error-by-error basis.

**Comment by howardroark** [comment]
I found a salt config that someone has made for their machine...

https://github.com/mafrosis/dotfiles/blob/master/salt/android/init.sls

Does this look it is heading down the right path?

**Comment by Jordann** [comment]
Yea this looks like it may solve the problems.

**Comment by howardroark** [comment]
Okay, ill keep plugging away here.  You keep thinking about the app and how
the state of the data could be bound to all activity.

**Comment by howardroark** [comment]
We are good!

After you provision the server and ssh in.

```
cd cordova
cordova build android
```

Then get the IP of the VM and visit here from an Android device...

http://android.X.X.X.X.xip.io/   (X.X.X.X = network IP)

Just click **HelloWorld-debug.apk**

You will need to uninstall any old versions first though.

**Comment by Jordann** [comment]
I get this error when running the commands you listed. Does the cordova www folder need to be symlinked to our public one?

```
(virtualenv)vagrant@mom-Jord:/vagrant$ cd cordova/
(virtualenv)vagrant@mom-Jord:/vagrant/cordova$ cordova build android
Downloading cordova library for android...
Download complete
shell.js: internal error
Error: ENOTDIR, not a directory '/vagrant/cordova/www'
    at Object.fs.readdirSync (fs.js:654:18)
    at /home/vagrant/.nvm/v0.10.26/lib/node_modules/cordova/node_modules/cordova
-lib/node_modules/shelljs/shell.js:162:10
    at Array.forEach (native)
    at _ls (/home/vagrant/.nvm/v0.10.26/lib/node_modules/cordova/node_modules/co
rdova-lib/node_modules/shelljs/shell.js:122:9)
    at /home/vagrant/.nvm/v0.10.26/lib/node_modules/cordova/node_modules/cordova
-lib/node_modules/shelljs/shell.js:1839:7
    at Array.forEach (native)
    at expand (/home/vagrant/.nvm/v0.10.26/lib/node_modules/cordova/node_modules
/cordova-lib/node_modules/shelljs/shell.js:1836:8)
    at Object._cp (/home/vagrant/.nvm/v0.10.26/lib/node_modules/cordova/node_mod
ules/cordova-lib/node_modules/shelljs/shell.js:300:13)
    at Object.cp (/home/vagrant/.nvm/v0.10.26/lib/node_modules/cordova/node_modu
les/cordova-lib/node_modules/shelljs/shell.js:1491:23)
    at Object.module.exports.update_www (/home/vagrant/.nvm/v0.10.26/lib/node_mo
dules/cordova/node_modules/cordova-lib/src/cordova/metadata/android_parser.js:31
3:15)
```

**Comment by howardroark** [comment]
It does, yes.  I thought it was though...

https://github.com/freesurface/mom/blob/master/cordova/www

I'll wipe mine clean and see what I get.

**Comment by Jordann** [comment]
I have that file too...

**Comment by howardroark** [comment]
If you cd into it on the vagrant machine do you get to the public folder?

I wonder if Windows has issues with Git and symlinks.

**Comment by Jordann** [comment]
it doesn't recongize it as a folder, just a file. Could be a windows problem.

**Comment by howardroark** [comment]
Perhaps we could make a build script in python or node that copies public to www.

That way you run "fab build android" and it runs everything.  I'll think on it.

**Comment by howardroark** [comment]
@Jordann Could you try creating a Windows symlink from the host and see if it registers on the guest...

http://superuser.com/questions/124679/how-do-i-create-a-link-in-windows-7-home-premium-as-a-regular-user?answertab=votes#125981

Basically the Windows git client turns symlinks into files with paths in them on checkout.

There is a very long and interesting conversation here about turning the files into symlinks as part of git hook on checkout.

**Comment by howardroark** [comment]
After more thinking... If the user needs admin rights to make any symlink it would still be a relatively futile effort to convert the symlinks as a git post script.

**Comment by Jordann** [comment]
so it may be better to make a build script that copies public to www?

**Comment by howardroark** [comment]
Yup.  I'll do that and make a fabric option that runs it all.
